### PR TITLE
fix: handling JSON strings containing numeric keys without quotation marks.

### LINKED ISSUE #3918: [BUG] 反序列化key没有引号时报错
### 问题描述
*反序列化key没有引号时报错*

### 环境信息
*请填写以下信息：*

 - OS信息：  [e.g.：Ubuntu]
 - JDK信息： [e.g.：Openjdk 1.8.0_312]
 - 版本信息：[e.g.：Fastjson2 2.0.43]
 

### 重现步骤
*如何操作可以重现该问题：*

```java
    static class A {
        private Map<Integer, Integer> a = new HashMap<>();

        public Map<Integer, Integer> getA() {
            return a;
        }

        public void setA(Map<Integer, Integer> a) {
            this.a = a;
        }
    }

    @Test
    public void test() {
        String body = "{\"a\":{1:1}}";
        String bodyB = "{\"b\":{1:1}}";
        com.alibaba.fastjson.JSON.parseObject(body, A.class); // OK
        com.alibaba.fastjson.JSON.parseObject(bodyB, A.class); // OK
        com.alibaba.fastjson2.JSON.parseObject(body, A.class); // OK
        com.alibaba.fastjson2.JSON.parseObject(bodyB, A.class); // fail
    }
```

### 期待的正确结果
对象中不存在b，期望忽略b。不报错

### 相关日志输出
com.alibaba.fastjson2.JSONException: not support unquoted name, offset 7, character 1, line 1, column 8, fastjson-version 2.0.43 {"b":{1:1}}

#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*

### PR DESCRIPTION
**Pull request by mengnankkkk**
### What this PR does / why we need it?
当 JSON 字符串中包含无引号的数字 key 时，fastjson2 的反序列化行为不一致
字段存在的时候可以正确处理无引号数字 key 的逻辑
字段不存在的时候无法处理
Close #3918

### Summary of your change
 在 skipObject 方法中添加对无引号数字 key 的处理逻辑 在utf16/utf-8中
添加对应的测试文件，复现issue

#### Please indicate you've done the following:

- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

File: core/src/main/java/com/alibaba/fastjson2/JSONReaderUTF16.java [hunk 1]
```diff
@@ -3357,7 +3357,50 @@ private static int skipObject(JSONReaderUTF16 jsonReader, char[] bytes, int offs
             if (i != 0 && !jsonReader.comma) {
                 throw jsonReader.valueError();
             }
-            offset = skipName(jsonReader, bytes, offset, end);
+
+            char ch = jsonReader.ch;
+            if ((ch >= '0' && ch <= '9') || ch == '-' || ch == '+') {
+                // skip
```
Comment (wenshao) [inline core/src/main/java/com/alibaba/fastjson2/JSONReaderUTF16.java]: 这里可以重用skipNumber么
